name: polls
description: Polls for developers.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: 0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.8.1
  test: 1.15.0
  mockito: 3.0.2
  faker: 1.3.0

flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700